# 建数据库
CREATE DATABASE IF NOT EXISTS `message_system` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
# 使用数据库message_system
USE `message_system`;

# 删除表
DROP TABLE IF EXISTS `producer`;

# 建表语句
CREATE TABLE IF NOT EXISTS `producer` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  `name` VARCHAR(20) NOT NULL COMMENT '生产者名',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT '生产者信息表';

CREATE TABLE IF NOT EXISTS `consumer` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  `name` VARCHAR(20) NOT NULL COMMENT '消费者名',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT '消费者信息表';

CREATE TABLE IF NOT EXISTS `destination` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  `name` VARCHAR(20) NOT NULL COMMENT 'destination名',
  `type` INT NOT NULL DEFAULT 0 COMMENT '类型 0：topic 1：queue',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT 'MQ destination信息表';

CREATE TABLE IF NOT EXISTS `producer_destination` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  `producer_id` BIGINT NOT NULL COMMENT '生产者id',
  `destination_id` BIGINT NOT NULL COMMENT 'destination_id',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT '生产者destination关系信息表';

CREATE TABLE IF NOT EXISTS `consumer_destination` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  `consumer_id` BIGINT NOT NULL COMMENT '消费者id',
  `destination_id` BIGINT NOT NULL COMMENT 'destination_id',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT '消费者destination关系信息表';